espace_eleve:
    resource: "@ISIBundle/Resources/config/routing/espace-eleve.yml"
    prefix:   /espace-eleve

affaires_scolaires:
    resource: "@ISIBundle/Resources/config/routing/affaires-scolaires.yml"
    prefix:   /affaires-scolaires

parametres:
    resource: "@ISIBundle/Resources/config/routing/parametres.yml"
    prefix:   /parametres

internat:
    resource: "@ISIBundle/Resources/config/routing/internat.yml"
    prefix:   /internat

etude:
    resource: "@ISIBundle/Resources/config/routing/etude.yml"
    prefix:   /etude

import-export:
    resource: "@ISIBundle/Resources/config/routing/import-export.yml"
    prefix:   /import-export

disposition:
    resource: "@ISIBundle/Resources/config/routing/disposition.yml"
    prefix:   /disposition

#------------------------------------ ESPACE CORAN ---------------------------------------
# Page d'accueil des l'espace coran, ceux qui ne font que mémoriser le coran

    
#------------------------------ FIN DES ROUTES ESPACE CORAN ---------------------------------


#--------------------------------------- GESTION DU PROFIL ---------------------------------------
#Routes pour la gestion de son profil


#--------------------------------- FIN DES ROUTES GESTION DU PROFIL -----------------------------------



#---------------------------------- COMPTE D'UTILISATEURE ----------------------------------


#---------------------- FIN DES ROUTES POUR LES COMPTES D'UTILISATEURE ---------------------

#--------------------------------------- PANEL ADMIN ---------------------------------------
#Routes pour la gestion de son profil

#--------------------------------- FIN DES ROUTES PANEL ADMIN -----------------------------------



#------------------------------- DEBUT DES ROUTES DIVERS -----------------------------------

#-------------------------------- FIN DES ROUTES DIVERS -----------------------------------
