Absence:
    type: entity
    table: absence
    indexes:
        eleve_id:
            columns:
                - eleve_id
        annee_scolaire_id:
            columns:
                - annee_scolaire_id
        IDX_765AE0C9A1737417:
            columns:
                - reference_mois
    id: {  }
    fields:
        heureAbsence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: heure_absence
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    oneToOne:
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
        eleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_id:
                    referencedColumnName: eleve_id
            orphanRemoval: false
        referenceMois:
            targetEntity: Mois
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reference_mois:
                    referencedColumnName: reference_mois
            orphanRemoval: false
    lifecycleCallbacks: {  }
