Commettre:
    type: entity
    table: commettre
    indexes:
        probleme_id:
            columns:
                - probleme_id
        annee_scolaire_id:
            columns:
                - annee_scolaire_id
        IDX_1281ABA0A6CC7B2:
            columns:
                - eleve_id
    id: {  }
    oneToOne:
        eleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_id:
                    referencedColumnName: eleve_id
            orphanRemoval: false
        probleme:
            targetEntity: Probleme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                probleme_id:
                    referencedColumnName: probleme_id
            orphanRemoval: false
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
