Regimeformation:
    type: entity
    table: regimeformation
    id:
        regimeRef:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            id: true
            column: regime_ref
            generator:
                strategy: IDENTITY
    fields:
        libellefr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelleFr
        libellear:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelleAr
    lifecycleCallbacks: {  }
