<?php

namespace ISI\ORGBundle\Repository;

/**
 * ActivitePaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitePaysRepository extends \Doctrine\ORM\EntityRepository
{
}
