<?php

namespace ISI\ORGBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{

  public function getActivites()
  {
      $qb = $this->createQueryBuilder('a');

      $qb->select('a')
         ->orderBy('a.createdAt', 'DESC')
      ;
      return $qb
          ->getQuery()
          // ->getResult()
      ;
  }

}
