<?php

namespace ISI\ORGBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{

  public function getActivites()
  {
      $qb = $this->createQueryBuilder('a');

      $qb->select('a')
         ->join('a.commune', 'c')
         ->addSelect('c')
         ->join('c.ville', 'v')
         ->addSelect('v')
         ->where('v.id = :id')
         ->orderBy('a.createdAt', 'DESC')
         ->setParameter(':id', 105)
      ;
      return $qb
          ->getQuery()
          // ->getResult()
      ;
  }

}
