<?php

namespace ISI\ORGBundle\Repository;

/**
 * ActiviteTourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteTourneeRepository extends \Doctrine\ORM\EntityRepository
{
}
