<?php

namespace ISI\ORGBundle\Repository;

/**
 * ConvertiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvertiRepository extends \Doctrine\ORM\EntityRepository
{
}
