<?php

namespace ISI\ORGBundle\Repository;

/**
 * TourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourneeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTournees()
    {
        $qb = $this->createQueryBuilder('t');

        $qb->select('t')
           ->orderBy('t.createdAt', 'DESC')
        ;
        return $qb
            ->getQuery()
            // ->getResult()
        ;
    }
}
