<?php

namespace ISI\ORGBundle\Repository;

/**
 * TourneeCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourneeCommuneRepository extends \Doctrine\ORM\EntityRepository
{
}
