<?php

namespace ISI\ORGBundle\Repository;

/**
 * TourneePaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourneePaysRepository extends \Doctrine\ORM\EntityRepository
{
}
