Anneescolaire:
    type: entity
    table: anneescolaire
    indexes:
        libelleAnneeScolaire:
            columns:
                - libelle_annee_scolaire
    id:
        anneeScolaireId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: annee_scolaire_id
            generator:
                strategy: IDENTITY
    fields:
        libelleAnneeScolaire:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_annee_scolaire
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    lifecycleCallbacks: {  }
