Chambre:
    type: entity
    table: chambre
    id:
        chambreId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: chambre_id
            generator:
                strategy: IDENTITY
    fields:
        libelleChambre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: libelle_chambre
        numeroChambre:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: numero_chambre
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    lifecycleCallbacks: {  }
