Classe:
    type: entity
    table: classe
    indexes:
        annee_scolaire_classe_fk:
            columns:
                - annee_scolaire_id
        niveau_id:
            columns:
                - niveau_id
    id:
        classeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: classe_id
            generator:
                strategy: IDENTITY
    fields:
        libelleFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_classe_fr
        libelleClasseAr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_classe_ar
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
        niveau:
            targetEntity: Niveau
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                niveau_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
