Enseignement:
    type: entity
    table: enseignement
    indexes:
        annee_scolaire_id:
            columns:
                - annee_scolaire_id
        matiere_id:
            columns:
                - matiere_id
        classe_id:
            columns:
                - niveau_id
    uniqueConstraints:
        enseignement:
            columns:
                - niveau_id
                - annee_scolaire_id
                - matiere_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        coefficient:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        statuMatiere:
            type: boolean
            nullable: false
            column: statu_matiere
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
        matiere:
            targetEntity: Matiere
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                matiere_id:
                    referencedColumnName: matiere_id
            orphanRemoval: false
        niveau:
            targetEntity: Niveau
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                niveau_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
