Examen:
    type: entity
    table: examen
    indexes:
        anneescolaire_examen_fk:
            columns:
                - annee_scolaire_id
    id:
        examenId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: examen_id
            generator:
                strategy: IDENTITY
    fields:
        libelleFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_fr
        libelleAr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_ar
        dateProclamationResultats:
            type: date
            nullable: false
            column: date_proclamation_resultats
    manyToOne:
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
