Frequenter:
    type: entity
    table: frequenter
    indexes:
        eleve_id:
            columns:
                - eleve_id
        classe_id:
            columns:
                - classe_id
        matiere_id:
            columns:
                - matiere_id
        annee_scolaire_id:
            columns:
                - annee_scolaire_id
    uniqueConstraints:
        frequenter:
            columns:
                - annee_scolaire_id
                - eleve_id
                - classe_id
                - matiere_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        admission:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        datePreinscription:
            type: date
            nullable: false
            column: date_preinscription
        dateInscription:
            type: date
            nullable: false
            column: date_inscription
        validation:
            type: boolean
            nullable: false
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        eleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_id:
                    referencedColumnName: eleve_id
            orphanRemoval: false
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
        matiere:
            targetEntity: Matiere
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                matiere_id:
                    referencedColumnName: matiere_id
            orphanRemoval: false
        classe:
            targetEntity: Classe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                classe_id:
                    referencedColumnName: classe_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
