Groupeformation:
    type: entity
    table: groupeformation
    indexes:
        reference_regime:
            columns:
                - reference_regime
    uniqueConstraints:
        libelle_ar:
            columns:
                - libelle_ar
        sigle:
            columns:
                - sigle
        libelle_fr:
            columns:
                - libelle_fr
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelleFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_fr
        libelleAr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_ar
        sigle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        referenceRegime:
            targetEntity: Regimeformation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reference_regime:
                    referencedColumnName: regime_ref
            orphanRemoval: false
    lifecycleCallbacks: {  }
