Interner:
    type: entity
    table: interner
    indexes:
        eleve_id:
            columns:
                - eleve_id
        annee_scolaire_id:
            columns:
                - annee_scolaire_id
        chambre_id:
            columns:
                - chambre_id
    uniqueConstraints:
        interner:
            columns:
                - chambre_id
                - eleve_id
                - annee_scolaire_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        anneeScolaire:
            targetEntity: Anneescolaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                annee_scolaire_id:
                    referencedColumnName: annee_scolaire_id
            orphanRemoval: false
        eleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_id:
                    referencedColumnName: eleve_id
            orphanRemoval: false
        chambre:
            targetEntity: Chambre
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chambre_id:
                    referencedColumnName: chambre_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
