Matiere:
    type: entity
    table: matiere
    indexes:
        languematiere_matiere_fk:
            columns:
                - reference_langue
    id:
        matiereId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: matiere_id
            generator:
                strategy: IDENTITY
    fields:
        libelleMatiere:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_matiere
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        referenceLangue:
            targetEntity: Languematiere
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reference_langue:
                    referencedColumnName: reference_langue
            orphanRemoval: false
    lifecycleCallbacks: {  }
