Niveau:
    type: entity
    table: niveau
    indexes:
        groupe_formation_id:
            columns:
                - groupe_formation_id
    uniqueConstraints:
        libelle_fr:
            columns:
                - libelle_fr
        libelle_ar:
            columns:
                - libelle_ar
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelleFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_fr
        libelleAr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: libelle_ar
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        groupeFormation:
            targetEntity: Groupeformation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                groupe_formation_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
