Note:
    type: entity
    table: note
    indexes:
        examen_id:
            columns:
                - examen_id
        matiere_id:
            columns:
                - matiere_id
        eleve_id:
            columns:
                - eleve_id
    uniqueConstraints:
        note:
            columns:
                - eleve_id
                - matiere_id
                - examen_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: integer
            nullable: false
            options:
                unsigned: false
        appreciationFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: appreciation_fr
        appreciationAr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: appreciation_ar
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    manyToOne:
        examen:
            targetEntity: Examen
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                examen_id:
                    referencedColumnName: examen_id
            orphanRemoval: false
        eleve:
            targetEntity: Eleve
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_id:
                    referencedColumnName: eleve_id
            orphanRemoval: false
        matiere:
            targetEntity: Matiere
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                matiere_id:
                    referencedColumnName: matiere_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
