Probleme:
    type: entity
    table: probleme
    id:
        problemeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: probleme_id
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateSave:
            type: datetime
            nullable: false
            column: date_save
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
    lifecycleCallbacks: {  }
