imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ISIBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ORGBundle/Resources/config/services.yml" }
    
    # Put parameters here that don't need to change on each machine where the app is deployed
    # https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    dossier_photos_eleves: '%kernel.project_dir%/web/photos/eleves'
    dossier_photos_enseignants: '%kernel.project_dir%/web/photos/enseignants'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # globals:
    #     pathToWeb: "%kernel.root_dir%/../web"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                mapping_types:
                    bit: boolean
            customer:
                driver:   pdo_mysql
                host:     '%database_host2%'
                port:     '%database_port2%'
                dbname:   '%database_name2%'
                user:     '%database_user2%'
                password: '%database_password2%'
                charset:  UTF8
        # driver: pdo_mysql
        # host: '%database_host%'
        # port: '%database_port%'
        # dbname: '%database_name%'
        # user: '%database_user%'
        # password: '%database_password%'
        # charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        # default_entity_manager: default
        # entity_managers:
        #     default:
        #         connection: default
        #         # mappings:
        #         #     AppBundle:  ~
        #         #     ISIBundle: ~
        #     customer:
        #         connection: customer
        #         # mappings:
        #         #     ISIBundle: ~
        # #auto_generate_proxy_classes: '%kernel.debug%'
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Windows Configuration for KnpSnappyBundle
knp_snappy:
    pdf:
        enabled: true
        binary: /usr/local/bin/wkhtmltopdf # "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" #
        options: []
    image:
        enabled: true
        binary: /usr/local/bin/wkhtmltoimage # "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" #
        options: []
    # temporary_folder: '%kernel.root_dir%/../web/pdf-temp'
    # temporary_folder: '%kernel.cache_dir%/snappy'

# # tcpdf
# white_october_tcpdf:
#     class: 'Acme\MyBundle\MyTCPDFClass'

# Config de FOSUserBundle
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User
    from_email:
        address:     "%mailer_user%"
        sender_name: "%mailer_user%"
    # registration:
    #     form:
    #         type: UserBundle\Form\RegistrationType

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/semantic_ui_pagination.html.twig'
        # pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
