# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User:                    sha512

    role_hierarchy:
        ROLE_NOTE:            ROLE_USER
        ROLE_ETUDE:           ROLE_USER
        ROLE_INTERNAT:        ROLE_USER
        ROLE_SCOLARITE:       ROLE_USER
        ROLE_ENSEIGNANT:      ROLE_USER
        ROLE_ORGANISATION:    ROLE_USER
        ROLE_ADMIN_SCOLARITE: ROLE_SCOLARITE
        ROLE_ADMIN_ANNEXE:    [ROLE_ADMIN_SCOLARITE, ROLE_ENSEIGNANT, ROLE_ETUDE]
        ROLE_SUPER_ADMIN:     [ROLE_ADMIN_SCOLARITE, ROLE_ENSEIGNANT, ROLE_ETUDE, ROLE_INTERNAT, ROLE_ORGANISATION, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            anonymous: true

        test:
            # pattern: ^/edit-user
            pattern: ^/add-users-test
            anonymous: true

        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/admin,    roles: ROLE_SUPER_ADMIN, ip: 127.0.0.1 }
        - { path: ^/register, roles: ROLE_SUPER_ADMIN, ip: 127.0.0.1 }
