<?php

namespace ISI\MSGBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMessages($from, $to)
    {
        $qb = $this->createQueryBuilder('m');

        $qb->select('m')
           ->join('m.fromId', 'f')
           ->addSelect('f')
           ->join('m.toId', 't')
           ->addSelect('t')
           ->where('(m.fromId = :from AND m.toId = :to) OR (m.fromId = :to AND m.toId = :from)')
           ->orderBy('m.createAt', 'DESC')
           ->setParameter('from', $from)
           ->setParameter('to', $to)
        ;
        return $qb
            ->getQuery()
            // ->getResult()
        ;
    }

    public function unReadCount(int $userId)
    {
        $qb = $this->createQueryBuilder('m');

        $qb->select('IDENTITY(m.fromId)', 'COUNT(m.id)')
           ->where('m.fromId = :userId AND m.readAt IS NULL')
           ->groupBy('m.fromId')
           ->setParameter('userId', $userId)
           
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            // ->getArrayResult()
            ;
    }
}
