#------------------------------- DEBUT DES ROUTES ENSEIGNANT -----------------------------------
ens_home:
    path:     /enseignant-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:index }
    requirements:
        as: \d+

ens_add:
    path:     /enseignant/ajouter-un-nouvel-enseignant-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:addEnseignant }
    requirements:
        as: \d+

ens_edit:
    path:     /enseignant/editer-un-enseignant-{as}-{enseignantId}.html
    defaults: { _controller: ENSBundle:Enseignant:editEnseignant }
    requirements:
        as: \d+
        enseignantId: \d+

ens_info:
    path:     /enseignant/information-sur-l-enseignant-{as}-{enseignantId}.html
    defaults: { _controller: ENSBundle:Enseignant:infoEnseignant }
    requirements:
        as: \d+
        enseignantId: \d+

ens_initialisation_prise_de_fonction:
    path:     /enseignant/initialisation-de-la-prise-de-fonction-d-un-enseignant-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:priseDeFonctionHome }
    requirements:
        as: \d+

ens_prise_de_fonction:
    path:     /enseignant/prise-de-fonction-de-l-enseignant-{as}-{enseignantId}.html
    defaults: { _controller: ENSBundle:Enseignant:priseDeFonction }
    requirements:
        as: \d+
        enseignantId: \d+

ens_fonctions_en_cours:
    path:     /enseignant/fonctions-d-en-enseignant-en-cours-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:fonctionEnCours }
    requirements:
        as: \d+

ens_initialisation_l_arret_de_fonction:
    path:     /enseignant/initialisation-de-l-arret-de-fonction-d-un-enseignant-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:arretDeFonctionHome }
    requirements:
        as: \d+

ens_arret_de_fonction:
    path:     /enseignant/arret-de-fonction-de-l-enseignant-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Enseignant:arretDeFonction }
    requirements:
        as: \d+
        contratId: \d+

ens_enseignant_de_l_annee:
    path:     /enseignant/enseignants-de-l-annee-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:enseignantsDeLAnnee }
    requirements:
        as: \d+

ens_impression_liste_des_enseignants:
    path:     /enseignant/impression-de-la-liste-des-enseignants-de-l-annee-{as}.html
    defaults: { _controller: ENSBundle:Enseignant:impressionListeDesEnseignantsDeLAnnee }
    requirements:
        as: \d+

ens_impression_liste_des_enseignants_plus_de_details:
    path:     /enseignant/impression-de-la-liste-des-enseignants-de-l-annee-avec-plus-de-details{as}.html
    defaults: { _controller: ENSBundle:Enseignant:impressionListeDesEnseignantsDeLAnneeAvecDetails }
    requirements:
        as: \d+

ens_ajouter_a_l_annee:
    path:     /enseignant/ajouter-cet-enseignant-pour-l-annee-en-cours-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Enseignant:ajouterEnseignantAnnee }
    requirements:
        as: \d+
        contratId: \d+

ens_edit_enseignant_annee:
    path:     /enseignant/mise-a-jour-un-enseignant-pour-l-annee-en-cours-{as}-{anneeContratId}.html
    defaults: { _controller: ENSBundle:Enseignant:modifierEnseignantAnnee }
    requirements:
        as: \d+
        anneeContratId: \d+

ens_retards_home:
    path:     /enseignant/page-d-accueil-des-retards-des-enseignants-{as}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:indexRetards }
    requirements:
        as: \d+

ens_saisi_retards:
    path:     /enseignant/page-de-saisie-des-retards-des-enseignants-{as}-{periode}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:saisieDesRetards }
    requirements:
        as: \d+
        periode: Matin|Soir

ens_voir_retards_home:
    path:     /enseignant/apercu-des-retards-des-enseignants-enregistres-home-{as}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:apercuDesRetardsHome }
    requirements:
        as: \d+

ens_voir_retards_mois:
    path:     /enseignant/apercu-des-retards-des-enseignants-enregistres-pour-un-mois-donnee-{as}-{moisId}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:apercuDesRetardsMois }
    requirements:
        as: \d+
        moisId: \d+

ens_voir_retards_mois_cumul:
    path:     /enseignant/apercu-du-bilan-des-retards-des-enseignants-enregistres-pour-un-mois-donnee-{as}-{moisId}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:apercuDesRetardsMoisCumul }
    requirements:
        as: \d+
        moisId: \d+

ens_absences_home:
    path:     /enseignant/page-d-accueil-des-absences-des-enseignants-{as}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:indexAbsences }
    requirements:
        as: \d+

ens_enregistrer_absence:
    path:     /enseignant/page-d-accueil-d-absence-d-un-enseignant-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:enregistrerAbsence }
    requirements:
        as: \d+
        contratId: \d+

ens_voir_absences_home:
    path:     /enseignant/apercu-des-absences-des-enseignants-enregistrees-home-{as}.html
    defaults: { _controller: ENSBundle:AbsencesEtRetards:apercuDesAbsencesHome }
    requirements:
        as: \d+

ens_conduite_home:
    path:     /enseignant/conduite-home-{as}.html
    defaults: { _controller: ENSBundle:Discipline:indexConduite }
    requirements:
        as: \d+

ens_enregistrement_conduite:
    path:     /enseignant/enregistrer-une-conduite-pour-un-enseignant-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Discipline:enregistrerConduite }
    requirements:
        as: \d+
        contratId: \d+

ens_voir_conduite:
    path:     /enseignant/voir-les-conduites-d-un-enseignant-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Discipline:voirConduite }
    requirements:
        as: \d+
        contratId: \d+

ens_convocation_home:
    path:     /enseignant/convocation-home-{as}.html
    defaults: { _controller: ENSBundle:Discipline:indexConvocation }
    requirements:
        as: \d+

ens_convoquer_enseignant:
    path:     /enseignant/convoquer-des-enseignants-{as}.html
    defaults: { _controller: ENSBundle:Discipline:convoquerHome }
    requirements:
        as: \d+

ens_info_convocation:
    path:     /enseignant/rempli-convocation-des-enseignants-{as}.html
    defaults: { _controller: ENSBundle:Discipline:remplirConvocation }
    requirements:
        as: \d+

# ensConvocationId ici est le paramètre qui renvoi l'id de l'entité AnneeContratConvocation, qui correspond à l'enregistrement
# d'une convocation d'un enseignant pour une année donnée
ens_audition_et_verdict:
    path:     /enseignant/enregistrement-de-l-audition-et-du-verdict-pour-la-convocation-de-l-enseignant-{as}-{ensConvocationId}.html
    defaults: { _controller: ENSBundle:Discipline:auditionEtVerdict }
    requirements:
        as: \d+
        ensConvocationId: \d+

ens_sanction_home:
    path:     /enseignant/sanction-home-{as}.html
    defaults: { _controller: ENSBundle:Discipline:sanctionHome }
    requirements:
        as: \d+

ens_voir_sanction:
    path:     /enseignant/voir-les-sanctions-d-un-enseignant-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Discipline:voirSanction }
    requirements:
        as: \d+
        contratId: \d+

ens_add_sanction:
    path:     /enseignant/enregistrement-d-une-sanction-{as}-{contratId}.html
    defaults: { _controller: ENSBundle:Discipline:addSanction }
    requirements:
        as: \d+
        contratId: \d+

ens_rencontre_home:
    path:     /enseignant/index-des-rencontres-{as}.html
    defaults: { _controller: ENSBundle:Rencontre:index }
    requirements:
        as: \d+

ens_add_rencontre:
    path:     /enseignant/enregistrement-de-rencontres-{as}.html
    defaults: { _controller: ENSBundle:Rencontre:addRencontre }
    requirements:
        as: \d+

ens_edit_rencontre:
    path:     /enseignant/mise-a-jour-des-informations-d-une-rencontre-{as}-{rencontreId}.html
    defaults: { _controller: ENSBundle:Rencontre:editRencontre }
    requirements:
        as: \d+
        rencontreId: \d+

ens_participants_rencontre:
    path:     /enseignant/ajouter-des-participants-a-la-rencontre-{as}-{rencontreId}.html
    defaults: { _controller: ENSBundle:Rencontre:participantsRencontre }
    requirements:
        as: \d+
        rencontreId: \d+

ens_liste_des_participants:
    path:     /enseignant/liste-des-participants-a-la-rencontre-{as}-{rencontreId}.html
    defaults: { _controller: ENSBundle:Rencontre:listeDesParticipantsRencontre }
    requirements:
        as: \d+
        rencontreId: \d+

# Routes pour les cours
ens_liste_des_classes_save_cours:
    path:     /enseignant/cours/liste-des-classes/{as}/{regime}
    defaults: { _controller: ENSBundle:Cours:listeDesClassesSaveCours }
    requirements:
        as: \d+
        regime: A|F

ens_enregistrer_cours_classe:
    path:     /enseignant/cours/enregistrement-de-cours/{as}/{regime}/{classeId}
    defaults: { _controller: ENSBundle:Cours:enregistrerCoursDuneClasse }
    requirements:
        as      : \d+
        regime  : A|F
        classeId: \d+

ens_cours_de_la_classe:
    path:     /enseignant/cours/liste-des-cours-de-la-classe/{as}/{regime}/{classeId}
    defaults: { _controller: ENSBundle:Cours:voirLesCoursDeLaClasse }
    requirements:
        as      : \d+
        regime  : A|F
        classeId: \d+

ens_nombre_heures_cours_enseignants:
    path:     /enseignant/cours/nombre-heures-de-cours-des-enseignants/{as}
    defaults: { _controller: ENSBundle:Cours:nombreHeuresCoursEnseignants }
    requirements:
        as      : \d+

ens_cours_d_un_enseignant:
    path:     /enseignant/cours/cours-d-un-enseignant/{as}/{anneeContratId}
    defaults: { _controller: ENSBundle:Cours:coursDUnEnseignant }
    requirements:
        as: \d+
        anneeContratId: \d+
#-------------------------------- FIN DES ROUTES ENSEIGNANT -----------------------------------
