<?php

namespace ISI\ISIBundle\Repository;

/**
 * AnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnexeRepository extends \Doctrine\ORM\EntityRepository
{
}
