<?php

namespace ISI\ISIBundle\Repository;

/**
 * ChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambreRepository extends \Doctrine\ORM\EntityRepository
{
  public function chambresDisponibles($genre)
  {
    $qb = $this->createQueryBuilder('c');
    $qb->where('c.placesDisponibles > 0 AND c.genre = :genre');
    $qb->setParameter('genre', $genre);

    return $qb->getQuery()
              ->getResult();
  }
}
