<?php

namespace ISI\ISIBundle\Repository;

/**
 * EleverenvoyeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleverenvoyeRepository extends \Doctrine\ORM\EntityRepository
{
    public function dernierRenvoi($eleveId)
    {
        $qb = $this->createQueryBuilder('er');

        $offset = 0;
        $limit = 1;
        $qb->select('er')
           ->where('er.eleve = :eleveId')
           ->orderBy('er.id', 'DESC')
           ->setFirstResult($offset)
           ->setMaxResults($limit)
           ->setParameter('eleveId', $eleveId)
        ;
        return $qb
           ->getQuery()
           ->getOneOrNullResult()
        // ->getResult()
        ;
    }
}
