<?php

namespace ISI\ISIBundle\Repository;

/**
 * ElevereintegreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevereintegreRepository extends \Doctrine\ORM\EntityRepository
{
    
}
