<?php

namespace ISI\ISIBundle\Repository;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends \Doctrine\ORM\EntityRepository
{
}
