<?php

namespace ISI\ISIBundle\Repository;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends \Doctrine\ORM\EntityRepository
{
  public function enseignementDuNiveau($anneeId, $niveauId, $enfant = false)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->join('e.niveau', 'n')
       ->addSelect('n')
       ->join('e.matiere', 'm')
       ->addSelect('m')
       ->join('e.annee', 'an')
       ->addSelect('an')
       ->orderBy('m.id', 'ASC');
    if($enfant == false)
        $qb->where('an.id = :anneeId AND n.id = :niveauId AND m.matiere_mere IS NULL');
    if($enfant == true)
        $qb->where('an.id = :anneeId AND n.id = :niveauId AND m.matiere_mere IS NOT NULL');

    $qb->setParameters(['anneeId' => $anneeId, 'niveauId' => $niveauId]);
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function matieresDeCompositionDuNiveau($as, $niveauId)
  {
    $qb = $this->createQueryBuilder('e');
    $qb->join('e.matiere', 'm')
       ->join('e.niveau', 'n')
       ->join('e.annee', 'an')
       ->orderBy('m.id', 'ASC');
       $qb->where('an.id = :annee AND n.id = :niveau AND e.matiereExamen = true AND m.matiere_mere IS NULL');

    $qb->setParameters(['annee' => $as, 'niveau' => $niveauId]);
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
