<?php

namespace ISI\ISIBundle\Repository;

/**
 * FrequenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrequenterRepository extends \Doctrine\ORM\EntityRepository
{

    public function frequenterValidee($as)
    {
        $qb = $this->createQueryBuilder('f');
        // $admission = NULL;
        $qb->select('f')
           ->where('f.anneeScolaire = :as AND f.admission IS NULL')
           ->setParameter('as', $as);
        //    ->setParameter('admission', $admission);

        // return $qb->getDql();
        return $qb->getQuery()
                  ->getResult();
    }

    public function elevesDuRegime($as, $regime)
    {
        $qb = $this->createQueryBuilder('f');
        $grp = ($regime == 'A') ? 1 : 2 ;
        $qb->select('f')
           ->join('f.eleve', 'e')
           ->addSelect('e')
           ->join('f.classe', 'c')
           ->addSelect('c')
           ->join('c.niveau', 'n')
           ->addSelect('n')
           ->where('n.groupeFormation = :grp AND f.anneeScolaire = :as AND e.renvoye = 0')
           ->setParameter('grp', $grp)
           ->setParameter('as', $as);

        return $qb->getQuery()
                  ->getResult();
    }

    public function derniereFrequentation($eleveId)
    {
        $offset = 0;
        $limit = 1;
        $qb = $this->createQueryBuilder('f');
        $qb->select('f')
           ->join('f.eleve', 'e')
           ->addSelect('e')
           ->where('e.eleveId = :eleveId') 
           ->orderBy('f.id', 'DESC')
           ->setFirstResult( $offset )
           ->setMaxResults( $limit )
           ->setParameter('eleveId', $eleveId);

        return $qb->getQuery()
                  ->getResult();
    }
}
