<?php

namespace ISI\ISIBundle\Repository;

/**
 * MemoriserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoriserRepository extends \Doctrine\ORM\EntityRepository
{
    
}
