<?php

namespace ISI\ISIBundle\Repository;

/**
 * PaiementinternatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementinternatRepository extends \Doctrine\ORM\EntityRepository
{
  public function lesPaiementsDUneAnnee($as)
  {
    $qb = $this->createQueryBuilder('p');
    $qb->join('p.moisdepaiement', 'mdp')
       // ->addSelect('mdp')
       ->join('mdp.anneeScolaire', 'an')
       // ->addSelect('an')
       ->where('an.anneeScolaireId = :as')
       ->setParameter('as', $as);

    return $qb->getQuery()
              ->getResult();
  }
}
