<?php

namespace ISI\ISIBundle\Repository;

/**
 * ProgrammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeRepository extends \Doctrine\ORM\EntityRepository
{
    public function programmeDeLAnnee(int $anneeId)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.annee', 'a')
           ->where('a.id = :anneeId AND p.isDeleted = false')
           ->orderBy('p.debut', 'ASC')
           ->setParameter('anneeId', $anneeId)
        ;

        return $qb->getQuery()->getResult();
    }
    
    public function dateDansPeriodeDeCours($dateAppel)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.debut <= :dateAppel AND :dateAppel <= p.fin AND p.isPeriodeDeCours = false AND p.isDeleted = false')
           ->setParameter('dateAppel', $dateAppel)
        ;

        return $qb->getQuery()->getResult();
    }
}
