<?php

namespace ISI\ISIBundle\Repository;

/**
 * BatimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatimentRepository extends \Doctrine\ORM\EntityRepository
{
}
