<?php

namespace ISI\ISIBundle\Repository;

/**
 * SalleClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
