<?php

namespace ISI\ISIBundle\Repository;

/**
 * UserAnnexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnnexeRepository extends \Doctrine\ORM\EntityRepository
{
}
