#------------------------------------ AFFAIRES SCOLAIRES ---------------------------------------
isi_home_scolarite:
    path:     /index.html
    defaults: { _controller: ISIBundle:AffairesScolaires:homeScolarite }

#Routes pour les affaires scolaires
isi_affaires_scolaires:
    path:     /home-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:index }
    requirements:
        as:      \d+
        regime:  A|F

#(((((((((((((((( CLASSES ))))))))))))))))
# Accueil pour l'édition de liste de classe
isi_statistiques_regime:
    path:     /statistiques-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:statistiques }
    requirements:
        as:     \d+
        regime: A|F

# Accueil pour l'édition de liste de classe
isi_liste_de_classe_home:
    path:     /liste-de-classe-home-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDeClasseHome }
    requirements:
        as:     \d+
        regime: A|F

# Edition sans impression de la liste de classe d'une classe donnée
isi_tirer_liste_de_la_classe_edition_sans_impression:
    path:     /liste-de-la-classe-edition-sans-impression-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDeClasseEtatSansImpression }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Edition de la liste de classe d'une classe donnée
isi_tirer_liste_de_la_classe:
    path:     /liste-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:tirerListeDeLaClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Accueil pour l'édition de liste d'appel
isi_liste_d_appel_home:
    path:     /liste-d-appel-home-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDAppelHome }
    requirements:
        as:     \d+
        regime: A|F

# Edition de la liste d'appel' d'une classe donnée pdf
isi_tirer_liste_d_appel_de_la_classe_academie:
    path:     /liste-d-appel-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:tirerListeDAppelDeLaClasseAcademie }
    requirements:
        as:       \d+
        regime:   A
        classeId: \d+

# Edition de la liste d'appel' d'une classe donnée
isi_tirer_liste_d_appel_de_la_classe_formation:
    path:     /liste-d-appel-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:tirerListeDAppelDeLaClasseFormation }
    requirements:
        as:       \d+
        regime:   F
        classeId: \d+

liste_de_classe:
    path:     /liste-de-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDeClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Liste des halaqas pour lesquelles il y a des élèves durant cette année
isi_liste_des_halaqas:
    path:     /liste-de-halaqa-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDesHalaqas }
    requirements:
        as:       \d+
        regime:   A|C

# Liste des élèves d'une halaqa bien donnée
isi_liste_d_une_halaqa:
    path:     /liste-de-halaqa-{as}-{regime}-{halaqaId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:listeDesElevesDUneHalaqa }
    requirements:
        as:       \d+
        regime:   A|C
        halaqaId: \d+

#
isi_saisie_de_notes:
    path:     /accueil-saisie-de-notes-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:accueilSaisieDeNote }
    requirements:
        as:       \d+
        regime:   A|F


# Reamenager les classes: quand des classes doivent être jumeler par exemple
isi_reamenager_classes_home:
    path:     /reamenager-les-classes-home-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:AffairesScolaires:reamenagerClassesHome
    requirements:
        as:      \d+
        regime:  A|F

#
isi_reamenager_une_classe:
    path:     /reamenager-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:reamenagerUneClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

#
isi_appliquer_reamenagement:
    path:     /application-des-reamenagements-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:appliquerReamenagement }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Pour les résultats (calcul des moyennes, classement...)
isi_resultats_d_examens:
    path:     /examen/resultats-d-examen-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Examen:accueilResultatsDExamen }
    requirements:
        as:       \d+
        regime:   A|F

# Voir les données statistiques d'un examen donné
isi_statiqtiques:
    path:     /examen/donnees-statistiques-examen-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Examen:statistiques }
    requirements:
        as:       \d+
        regime:   A|F

# Voir les résultats annuels
isi_resultats_annuels:
    path:     /examen/resultats-annuels/{as}-{regime}.html
    defaults: { _controller: ISIBundle:Examen:resultatsAnnuels }
    requirements:
        as:       \d+
        regime:   A|F

# Cette route va afficher une classe en donnant nous donnant la
# possibilité de voir les notes annuelles, les bulletins et les statistiques
isi_resultats_annuels_d_une_classe:
    path: /examen/resultats-annuels-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:Examen:resultatsAnnuelsDeLaClasse }
    requirements:
        as:       \d+
        classeId: \d+
        regime:   A|F

# Afficher les notes des deux examens des élèves d'une classe donnée
isi_notes_des_deux_examens:
    path:     /examen/notes-de-tous-les-examens/{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:Examen:notesTousLesExamens }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Bulletins qui font le cumul des deux examens (1ère et 2ème session)
isi_bulletins_moyennes_annuelles:
    path:     /examen/bulletins-moyennes-annuelles/{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:Examen:bulletinsMoyennesAnnuelles }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Bulletin annuel d'un seul élève
isi_bulletin_annuel_individuel:
    path:     /examen/resultats-annuels-d-un-eleve-{as}-{regime}-{classeId}-{eleveId}.html
    defaults: { _controller: ISIBundle:Examen:bulletinAnnuelIndividuel }
    requirements:
        as:        \d+
        regime:    A|F
        classeId:  \d+
        eleveId:   \d+

# Ces statistiques prennent en compte les résultats des deux examens
isi_statistiques_annuelles:
    path:     /examen/statistiques-annuelles-de-la-classe-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:Examen:statistiquesAnnuellesDUneClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Route de deboggage pour les moyennes annuelles
moyenne_annuelle:
    path:     /moyennes-annuelles-de-la-classe.html
    defaults: { _controller: ISIBundle:Examen:resultYear }

# La route-ci nous permettra in chaa Allah de calculer les moyennes annuelles et de faire le classement annuel
isi_classement_annuel:
    path:     /examen/calcul-moyennes-annuelles-et-classement-annuel-{as}-{regime}-{classeId}.html
    defaults: { _controller: ISIBundle:Examen:moyennesClassementAnnuel }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

# Génération des données statistiques d'un examen donné
isi_generation_donnees_statiqtiques:
    path:     /examen/donnees-statistiques-examen-{as}-{regime}-{examenId}.html
    defaults: { _controller: ISIBundle:Examen:generationDonneesstatistiques }
    requirements:
        as:       \d+
        regime:   A|F
        examenId: \d+

# Afficher une classe pour pouvoir saisir les notes dans les différentes matières
isi_saisie_de_notes_de_la_classe:
    path:     /examen/liste-des-matieres-pour-la-saisie-des-notes-de-la-classe-{as}-{regime}-{classeId}-{examenId}.html
    defaults: { _controller: ISIBundle:Examen:saisieDesNotesDeLaClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        examenId: \d+

# Afficher une classe pour pouvoir saisir les notes dans les différentes matières
isi_resultats_de_la_classe:
    path:     /examen/resultats-de-la-classe-{as}-{regime}-{classeId}-{examenId}.html
    defaults: { _controller: ISIBundle:Examen:resultatsDeLaClasse }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        examenId: \d+

# La page d'accueil pour la gestion des absences (heures d'absence)
isi_accueil_gestion_absences:
    path:     /accueil-gestion-des-absences-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:absenceHome }
    requirements:
        as:     \d+
        regime: A|F

# Saisie des heures d'absences de la classe passée en paramètres
isi_heures_absences_d_une_classe_home:
    path:     /heures-d-absences-cours-de-la-classe-{as}-{regime}-{classeId}-{absence}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:heuresAbsenceCoursHome }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        absence:  Cours|Coran

# Affiche un formulaire pour permettre la saisie des heures d'absence
isi_saisie_des_heures_d_absence:
    path:     /saisie-des-heures-d-absence-{as}-{regime}-{classeId}-{absence}-{moisId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:saisieDesHeuresDAbsence }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        absence:  Cours|Coran
        moisId:   \d+

# Affiche un formulaire pour permettre la modification des heures d'absence
isi_modification_des_heures_d_absence:
    path:     /modification-des-heures-d-absence-{as}-{regime}-{classeId}-{absence}-{moisId}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:modificationDesHeuresDAbsence }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        absence:  Cours|Coran
        moisId:   \d+

# Voir les heures d'absence (heures d'absence)
isi_accueil_heures_enregistrees:
    path:     /accueil-heures-d-absences-enregistrees-{as}-{regime}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:absenceEnregistreeHome }
    requirements:
        as:     \d+
        regime: A|F

# Voir les heures d'absences d'une classe
isi_heures_absences_enregistrees:
    path:     /heures-d-absences-enregistrees-de-la-classe-{as}-{regime}-{classeId}-{absence}.html
    defaults: { _controller: ISIBundle:AffairesScolaires:heuresAbsenceEnregistrees }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        absence:  Cours|Coran

# La route pour la saisie des notes se trouve dans la partie examen

#------------------------------ FIN DES ROUTES AFFAIRES SCOLAIRES ---------------------------------
