#--------------------------------------- ESPACE ELEVE ---------------------------------------
#Routes pour l'espace élèves
isi_espace_eleve:
    path:     /index-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Eleve:index }
    requirements:
        as:     \d+
        regime: A|F

# Lien vers le fichier de remplissage
selection_eleves_regime:
    path:  /get/eleves/{regime}
    defaults: { _controller: ISIBundle:Eleve:selectionDesElevesDuRegime }
    requirements:
        regime: A|F|C
    options:
        expose: true

#Pour la préinscription (ajout) d'un nouvel élève
isi_preinscription:
    path :    /preinscription-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Eleve:preinscription }
    requirements:
        as:     \d+
        regime: A|F|C

#Pour l'édition (la mise à jour des informations) d'un élève
isi_edit_eleve:
    path:     /edit-eleve-{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:editEleve }
    requirements:
        as:     \d+
        id:     \d+
        regime: A|F|C

#Pour les informations relatives à un élève
isi_info_eleve:
    path:     /info-eleve-{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:infoEleve }
    requirements:
        as:     \d+
        id:     \d+
        regime: A|F|C

#Route pour voir tous les élèves inscrits
isi_eleves_inscrits:
    path:     /eleves-inscrits-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:Eleve:elevesInscrits
    requirements:
        as:      \d+
        regime:  A|F|C

#Route pour l'inscription d'un élève dans une classe
isi_inscription:
    path:     /inscription-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:Eleve:inscription
    requirements:
        as:      \d+
        regime:  A|F|C

# Route pour afficher la liste des élèves renvoyés
isi_eleves_renvoyes:
    path:     /eleves-renvoyes-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:Eleve:elevesRenvoyes
    requirements:
        as:      \d+
        regime:  A|F|C

# Pour renvoyer un élève
isi_renvoi_home:
    path:     /renvoi-home-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:Eleve:renvoiHome
    requirements:
        as:      \d+
        regime:  A|F|C

# Lancer le code de renvoi d'un élève
isi_renvoi:
    path:     /renvoyer-eleve-{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:renvoyer }
    requirements:
        as:      \d+
        regime:  A|F|C
        eleveId: \d+

# Lancer le code de renvoi d'un élève
isi_info_eleve_renvoye:
    path:     /informations-eleve-renvoye-{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:infoEleveRenvoye }
    requirements:
        as:      \d+
        regime:  A|F|C
        eleveId: \d+

# Pour pouvoir inscrire à nouveau un élève qu'on a renvoyé (au cours d'une même année)
isi_reintegration:
    path:     /reintegration-eleve-renvoye/{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:reintegrer }
    requirements:
        as:       \d+
        regime:   A|F|C
        eleveId:  \d+

# Pour pouvoir réintégrer un élève qu'on a renvoyé les années antérieures
isi_reintegrer_home:
    path:     /reintegrer-eleve-renvoye/{as}-{regime}-reintegration-home.html
    defaults: { _controller: ISIBundle:Eleve:reintegrerEleve }
    requirements:
        as:       \d+
        regime:   A|F|C

# La route qui permet d'afficher la liste des classes pour la modification
# de l'inscription d'un élève dans une classe
isi_modifier_inscription:
    path:     /liste-de-classe-pour-modification-inscription-d-un-eleve-{as}-{regime}.html
    defaults:
        _controller: ISIBundle:Eleve:editInscription
    requirements:
        as:      \d+
        regime:  A|F|C

# Affiche la liste des élèves de la classe pour modifier l'inscription d'un élève
isi_modifier_inscription_d_un_eleve:
    path:     /modification-inscription-d-un-eleve-{as}-{regime}-{classeId}.html
    defaults:
        _controller: ISIBundle:Eleve:modifierInscriptionDUnEleve
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+

isi_modifier_classe_eleve:
    path:     /modifier-la-classe-de-l-eleve-{as}-{regime}-{classeId}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:modifierClasseDeLEleve }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        eleveId:  \d+

# Pour la modification du niveau d'un élève qu'on à inscript
isi_modifier_niveau_eleve:
    path:     /modifier-le-niveau-de-l-eleve-{as}-{regime}-{classeId}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:modifierNiveauDeLEleve }
    requirements:
        as:       \d+
        regime:   A|F
        classeId: \d+
        eleveId:  \d+

# Changement de regime de formation (pour passer de l'academie au centre de formation par exemple)
isi_changer_regime_home:
    path:     /changement-de-regime-home-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Eleve:changerDeRegimeHome }
    requirements:
        as:     \d+
        regime: A|F|C

# Changement de regime de formation d'un élève donné
isi_changer_regime_eleve:
    path:     /changement-du-regime-de-l-eleve-{as}-{regime}-{eleveId}.html
    defaults: { _controller: ISIBundle:Eleve:changerDeRegimeDUnEleve }
    requirements:
        as:      \d+
        regime:  A|F
        eleveId: \d+

# Pour noter un problème concernant un élève
isi_problemes_home:
    path:     /signaler-un-probleme-home-{as}-{regime}.html
    defaults: { _controller: ISIBundle:Eleve:problemesHome }
    requirements:
        as:     \d+
        regime: A|F|C

# Enregistrement de la conduite d'un élève
isi_enregistrer_conduite:
    path:     /enregistrer-conduite-eleve/{as}-{regime}-{eleveId}-conduite.html
    defaults: { _controller: ISIBundle:Eleve:enregistrerConduite }
    requirements:
        as:      \d+
        regime:  A|F|C
        eleveId: \d+

# La fonction suivante a été mise en place juste pour une question de maintenance
# Des inscriptions ont été faites avant qu'on ne ajoute certaines matierès.
# Alors on va les ajoutées
ajout_de_frequenter:
    path:     /ajout-de-frequenter-pour-une-matiere-qui-n-a-pas-ete-ajoutee-avant-les-inscriptions-{as}-{regime}-{classeId}-{matiereId}.php
    defaults: { _controller: ISIBundle:Eleve:ajoutMatieresOublieesAvantInscription }
    requirements:
        as:        \d+
        classeId:  \d+
        matiereId: \d+
        regime:    A|F

ajout_de_notes:
    path:     /ajout-de-notes-pour-une-matiere-qui-n-a-pas-ete-ajoutee-après-la-generation-des-fiches-de-notes-{as}-{regime}-{classeId}-{matiereId}-{examenId}.php
    defaults: { _controller: ISIBundle:Eleve:ajoutNotesDesMatieresOublieesAvantInscription }
    requirements:
        as:        \d+
        classeId:  \d+
        matiereId: \d+
        examenId:  \d+
        regime:    A|F

eleves_sans_notes:
    path:     /ajouter-notes-des-eleve-sans-notes-{classeId}-{examenId}.html
    defaults: { _controller: ISIBundle:Eleve:AjouterNotesDesElevesSansNotes }
    requirements:
        examenId: \d+
        classeId: \d+

# La route suivante me permet d'accéder au fichier php pour voir les élèves d'un niveau qui ont des notes en manque
eleves_notes_incompletes:
    path:     /voir-notes-qui-manquent.html
    defaults: { _controller: ISIBundle:Eleve:elevesSansLesNotesAuCompletes }

# Lien pour la génération du fichier json contenant la description de l'élève dont le matricule a été saisi
eleve:
    path:      /eleve/{matricule}
    defaults: { _controller: ISIBundle:Eleve:eleve }
    options:
        expose: true

# Lien vers le fichier de remplissage
remplir_select_classe:
    path:  /get-classes-{anneeId}-{niveauId}
    defaults: { _controller: ISIBundle:Eleve:remplirClasse }
    options:
        expose: true

# Route ajax pour la récupération des matricules
get_matricule:
    path:     /get-matricule-{regime}
    defaults: { _controller: ISIBundle:Eleve:getMatricule }
    requirements:
        regime: A|F

#-------------------------------- FIN DES ROUTES ESPACE ELEVE ---------------------------------------
