#--------------------------------------- INTERNAT ---------------------------------------
#Routes pour la gestion de son profil
internat_home:
    path:     /internat-home-{as}.html
    defaults: { _controller: ISIBundle:Internat:index }
    requirements:
        as: \d+

# Gestion des chambres de l'internat
internat_gestion_chambres:
    path:     /gestion-des-chambres-{as}.html
    defaults: { _controller: ISIBundle:Internat:gestionDesChambres }
    requirements:
        as: \d+

# Ajout de chambres de l'internat
internat_add_chambre:
    path:     /ajouter-des-chambres-{as}.html
    defaults: { _controller: ISIBundle:Internat:addChambres }
    requirements:
        as: \d+

# Ajouter un(e) élève à l'internat
internat_add:
    path:     /ajouter-un-interne-home-{as}.html
    defaults: { _controller: ISIBundle:Internat:addInterne }
    requirements:
        as: \d+

# Ajouter un(e) élève à l'internat
internat_add_eleve:
    path:     /ajouter-un-eleve-a-l-internat-{as}-{eleveId}.html
    defaults: { _controller: ISIBundle:Internat:addEleveInternat }
    requirements:
        as:      \d+
        eleveId: \d+

#Pour les informations relatives à un élève
internat_info_eleve:
    path:     /info-eleve-{as}-{id}.html
    defaults: { _controller: ISIBundle:Internat:infoEleve }
    requirements:
        as:      \d+
        eleveId: \d+

# Cette route nous permettra d'ajouter les mois pris en compte pour le paiement des frais de l'internat
internat_add_mois_de_paiement:
    path:     /ajouter-les-mois-de-paiement-de-l-internat-{as}.html
    defaults: { _controller: ISIBundle:Internat:addMoisDePaiement }
    requirements:
        as: \d+

# Cette route va juste appliquer un enregistrement au niveau de la base de données
internat_add_mois_de_paie:
    path:     /ajouter-un-mois-de-paiement-{as}-{moisId}.html
    defaults: { _controller: ISIBundle:Internat:addLeMoisDePaie }
    requirements:
        as:     \d+
        moisId: \d+

# Ajouter un(e) élève à l'internat
internat_delete:
    path:     /retirer-un-interne-home-{as}.html
    defaults: { _controller: ISIBundle:Internat:deleteInterne }
    requirements:
        as: \d+

# Ajouter un(e) élève à l'internat
internat_delete_eleve:
    path:     /retirer-un-eleve-de-l-internat-{as}-{eleveId}.html
    defaults: { _controller: ISIBundle:Internat:deleteEleveInternat }
    requirements:
        as:      \d+
        eleveId: \d+

# Voir les élèves retirés de l'internat
internat_deleted:
    path:     /liste-des-eleves-retires-de-l-internat-{as}.html
    defaults: { _controller: ISIBundle:Internat:deletedEleves }
    requirements:
        as:      \d+
        eleveId: \d+

# Paiement des frais de l'internat - Accueil
internat_pay:
    path:     /paiement-des-frais-internat-{as}.html
    defaults: { _controller: ISIBundle:Internat:payInterneRight }
    requirements:
        as: \d+

# Paiement des frais de l'internat d'un élève donné pour un mois de paiement donné
internat_pay_mois:
    path:     /paiement-des-frais-internat-d-un-eleve-pour-un-mois-{as}-{eleveId}-{moisId}.html
    defaults: { _controller: ISIBundle:Internat:paiementDesFraisPourUnMois }
    requirements:
        as:      \d+
        moisId:  \d+
        eleveId: \d+

internat_recu_de_paiement:
    path:     /recu-de-paiement-{as}-{eleveId}-{moisId}-{paiementId}.html
    defaults: { _controller: ISIBundle:Internat:recuDePaiement }
    requirements:
        as:         \d+
        moisId:     \d+
        eleveId:    \d+
        paiementId: \d+


#--------------------------------- FIN DES ROUTES INTERNAT -----------------------------------