<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratRepository extends \Doctrine\ORM\EntityRepository
{
}
