<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratConduiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratConduiteRepository extends \Doctrine\ORM\EntityRepository
{
}
