<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratClasseRepository extends \Doctrine\ORM\EntityRepository
{
}
