<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratAbsenceRepository extends \Doctrine\ORM\EntityRepository
{
}
