<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratRetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratRetardRepository extends \Doctrine\ORM\EntityRepository
{
}
