<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratRencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratRencontreRepository extends \Doctrine\ORM\EntityRepository
{
}
