<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratRepository extends \Doctrine\ORM\EntityRepository
{
    public function fonctionDeLAnnee($anneeId, $annexeId)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a')
           ->join('a.annee', 'an')
           ->addSelect('an')
           ->join('a.contrat', 'c')
           ->addSelect('c')
           ->join('c.enseignant', 'e')
           ->addSelect('e')
           ->where('an.id = :anneeId AND c.fini = :bool AND e.enseignant = true AND e.annexe = :annexeId')
           ->orderBy('e.nomFr', 'ASC')
           ->addOrderBy('e.pnomFr', 'ASC')
           ->setParameter('anneeId', $anneeId)
           ->setParameter('annexeId', $annexeId)
           ->setParameter('bool', false)
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
