<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratSanctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratSanctionRepository extends \Doctrine\ORM\EntityRepository
{
}
