<?php

namespace ISI\ENSBundle\Repository;

/**
 * AnneeContratConvocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeContratConvocationRepository extends \Doctrine\ORM\EntityRepository
{
}
