<?php

namespace ISI\ENSBundle\Repository;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{
    public function dernierContrat($enseignantId)
    {
        $qb = $this->createQueryBuilder('c');
        $offset = 0;
        $limit = 1;
        $qb->select('c')
           ->join('c.enseignant', 'e')
           ->where('e.id = :idEns')
           ->orderBy('c.id', 'DESC')
           ->setFirstResult($offset)
           ->setMaxResults($limit)
           ->setParameter('idEns', $enseignantId)
        ;
        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            // ->getResult()
        ;
    }
}
