<?php

namespace ISI\ENSBundle\Repository;

/**
 * ConvocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvocationRepository extends \Doctrine\ORM\EntityRepository
{
}
