<?php

namespace ISI\ENSBundle\Repository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends \Doctrine\ORM\EntityRepository
{
}
