activites_externes:
    path:     /index-{as}
    defaults: { _controller: ORGBundle:ActiviteExterne:indexTournees }
    requirements:
        as: \d+

tournee.add:
    path:     /ajouter-une-tournee-{as}-{nationale}
    defaults: { _controller: ORGBundle:ActiviteExterne:addTourneesNationales }
    requirements:
        as: \d+
        nationale: \d+

tournee.edit:
    path:     /editer-une-tournee-nationale-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:editTourneesNationales }
    requirements:
        as: \d+
        id: \d+

destination.tournee.add.activite:
    path:     /liste-destinations-de-tournee-nationale-pour-enregistrement-activites-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:destinationPourAddActivitesTourneesNationale }
    requirements:
        as: \d+
        id: \d+

destination.tournee.internationale.add.activite:
    path:     /liste-destinations-de-tournee-internationale-pour-enregistrement-activites-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:destinationPourAddActivitesTourneesInternationale }
    requirements:
        as: \d+
        id: \d+

destination.tournee.remove.activite:
    path:     /suppression-destinations-de-tournee-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:destinationPourRemoveActivitesTourneesNationale }
    requirements:
        as: \d+
        id: \d+

destination.tournee.remove.action:
    path:     /suppression-destinations-de-tournee-{as}-{id}-{tourneeId}
    defaults: { _controller: ORGBundle:ActiviteExterne:delete }
    requirements:
        as: \d+
        id: \d+
        tourneeId: \d+

activite.tournee.add:
    path:     /ajouter-activite-pour-la-destination-de-tournee-{as}-{id}-{communeId}
    defaults: { _controller: ORGBundle:ActiviteExterne:addActivitesTourneesNationale }
    requirements:
        as: \d+
        id: \d+
        communeId: \d+

activite.tournee.internationale.add:
    path:     /ajouter-activite-pour-destination-de-tournee-internationale-{as}-{id}-{paysId}
    defaults: { _controller: ORGBundle:ActiviteExterne:addActivitesTourneesInternationale }
    requirements:
        as: \d+
        id: \d+
        paysId: \d+

tournee.internationale.add:
    path:     /ajouter-une-activite-internationale-{as}
    defaults: { _controller: ORGBundle:ActiviteExterne:addTourneesInternationales }
    requirements:
        as: \d+

tournee.info:
    path:     /informations-sur-une-tournee-nationale-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:infoTourneeNationale }
    requirements:
        as: \d+
        id: \d+

tournee.internationale.info:
    path:     /informations-sur-une-tournee-internationale-{as}-{id}
    defaults: { _controller: ORGBundle:ActiviteExterne:infoTourneeInternationale }
    requirements:
        as: \d+
        id: \d+
