disposition_home:
    path:     /index-{as}
    defaults: { _controller: ORGBundle:Disposition:index }
    requirements:
        as: \d+

batiment_home:
    path:     /gestions-des-batiments-{as}
    defaults: { _controller: ORGBundle:Disposition:gestionDesBatiments }
    requirements:
        as: \d+

batiment_add:
    path:     /ajouter-un-batiment-{as}
    defaults: { _controller: ORGBundle:Disposition:addBatiment }
    requirements:
        as: \d+

batiment_edit:
    path:     /editer-informations-batiment-{as}-{id}
    defaults: { _controller: ORGBundle:Disposition:editBatiment }
    requirements:
        as: \d+
        id: \d+

salle_home:
    path:     /gestions-des-salles-{as}
    defaults: { _controller: ORGBundle:Disposition:gestionDesSalles }
    requirements:
        as: \d+

salle_add:
    path:     /ajouter-un-salle-{as}
    defaults: { _controller: ORGBundle:Disposition:addSalle }
    requirements:
        as: \d+

salle_edit:
    path:     /editer-informations-salle-{as}-{id}
    defaults: { _controller: ORGBundle:Disposition:editSalle }
    requirements:
        as: \d+
        id: \d+

disposition:
    path:     /disposition-des-classes-par-salles-{as}
    defaults: { _controller: ORGBundle:Disposition:disposition }
    requirements:
        as: \d+

disposition_add:
    path:     /disposition-de-classes-en-salle-{as}-{id}
    defaults: { _controller: ORGBundle:Disposition:dispositionDeClasseEnSalle }
    requirements:
        as: \d+
        id: \d+

disposition_edit:
    path:     /editer-disposition-de-classes-en-salle-{as}-{id}
    defaults: { _controller: ORGBundle:Disposition:editerDispositionDeClasseEnSalle }
    requirements:
        as: \d+
        id: \d+