org_homepage:
    path:     /index-{as}
    defaults: { _controller: ORGBundle:Default:index }
    requirements:
        as: \d+

localites:
    resource: "@ORGBundle/Resources/config/routing/localite.yml"
    prefix:   /localites

mosquee:
    resource: "@ORGBundle/Resources/config/routing/mosquee.yml"
    prefix:   /mosquees

imam:
    resource: "@ORGBundle/Resources/config/routing/imam.yml"
    prefix:   /imam

conversion:
    resource: "@ORGBundle/Resources/config/routing/conversion.yml"
    prefix:   /conversion

vendredi:
    resource: "@ORGBundle/Resources/config/routing/vendredi.yml"
    prefix:   /vendredi

activite_locale:
    resource: "@ORGBundle/Resources/config/routing/activite-locale.yml"
    prefix:   /activite-locale

activite_externe:
    resource: "@ORGBundle/Resources/config/routing/activite-externe.yml"
    prefix:   /activite-externe

cours:
    resource: "@ORGBundle/Resources/config/routing/cours.yml"
    prefix:   /cours

disposition:
    resource: "@ORGBundle/Resources/config/routing/disposition.yml"
    prefix:   /disposition
